### ISSUE TITLE
with the sidebar open the team page will miss one column.

### ISSUE THREAD

**Issue by krshubham** [vatsals/Voloc-Web#1]
![screenshot from 2016-06-06 18-11-10](https://cloud.githubusercontent.com/assets/16729005/15822259/4ae2c398-2c12-11e6-9683-55811992fdf7.png)
![screenshot from 2016-06-06 18-11-12](https://cloud.githubusercontent.com/assets/16729005/15822260/4c15a3ac-2c12-11e6-97d5-343abd0254dd.png)

Should I make it scrollable to the right side?

**Comment by vatsals** [comment]
set the left navbar's attachment fixed and make the right side scrollable

**Comment by vatsals** [comment]
set the left navbar's attachment to fixed and make right side scrollable

**Comment by krshubham** [comment]
The top row in the about page doesn't match properly with the other rows. there is a slight position mismatch. Tell someone who made the page to check this page once again.

**Comment by vatsals** [comment]
that won't be a problem just put 5 images in a row instead of 6 but make sure that `there is no overflow-x. Set the width of images equally and set overflow-x: hidden;
